# Generated by Django 2.2 on 2023-01-10 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20230110_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
