# Generated by Django 2.2 on 2023-01-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20230111_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
