# Generated by Django 2.2 on 2023-01-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='SDE'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(default='MountBlue', max_length=200),
        ),
    ]
