# Generated by Django 2.2 on 2023-01-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_certificates_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic/amir.jpeg', upload_to='profile_pic'),
        ),
    ]
