# Generated by Django 2.2 on 2023-01-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0009_auto_20230103_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic/default.png', upload_to='profile_pic'),
        ),
    ]
