# Generated by Django 2.2 on 2023-01-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_friendlist_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='sender',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
