# Generated by Django 2.2 on 2023-01-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='followers',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
