# Generated by Django 2.2 on 2023-01-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_auto_20230105_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='discription',
            new_name='description',
        ),
    ]
