# Generated by Django 2.2 on 2023-01-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_auto_20230105_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='Microsoft', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(default='Backend Developer', max_length=200),
        ),
    ]
