# Generated by Django 2.2 on 2023-01-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_auto_20230106_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(default='company', max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='title',
            field=models.CharField(default='title', max_length=200),
        ),
    ]
