# Generated by Django 2.2 on 2023-01-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_auto_20230106_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pic/default_cover_pic.jpeg', upload_to='profile_pic'),
        ),
    ]
