# Generated by Django 2.2 on 2023-01-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_auto_20230106_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(default='profile_pic/default_exp_img.png', upload_to='profile_pic'),
        ),
    ]
