# Generated by Django 2.2 on 2023-01-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_auto_20230106_0549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='details',
        ),
        migrations.AddField(
            model_name='education',
            name='college',
            field=models.CharField(default='LPU', max_length=300),
        ),
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.CharField(default='B.Tech, CSE', max_length=300),
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.CharField(default='Present', max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.ImageField(default='profile_pic/default_cover_pic.jpeg', upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='education',
            name='starting_date',
            field=models.CharField(default='July 2019', max_length=200),
        ),
    ]