# Generated by Django 2.2 on 2023-01-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_auto_20230106_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(default='profile_pic/lpu.jpeg', upload_to='profile_pic'),
        ),
    ]
