# Generated by Django 2.2 on 2023-01-06 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0026_auto_20230106_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
