# Generated by Django 2.2 on 2023-01-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0027_auto_20230106_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(default='profile_pic/default_cover_pic.jpeg', upload_to='profile_pic'),
        ),
    ]
