# Generated by Django 4.1.5 on 2023-01-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0029_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.ImageField(blank=True, default='profile_pic/default_cover_pic.jpeg', null=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(blank=True, default='profile_pic/lpu.jpeg', null=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image',
            field=models.ImageField(blank=True, default='profile_pic/default_exp_img.png', null=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, default='profile_pic/default_cover_pic.jpeg', null=True, upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_pic/default_cover_pic.jpeg', null=True, upload_to='profile_pic'),
        ),
    ]
